### ISSUE TITLE
Update/get bios for all organizers

### ISSUE THREAD

**Issue by dcwalk** [ournetworks/2020#13]
We should update the organizers bios! they need to go on the website! Stored as a data file as yml:
https://github.com/ournetworks/ournetworks.ca/blob/master/_data/organizers.yml

@RangerMauve and @eggfroufrou can you look at what is there and draft one? Happy to assist!

TODOs:

- [x] sign off/update/add bios:
  - [x] @RangerMauve 
  - [x] @eggfroufrou 
  - [x] @garrying
  - [x] @dcwalk
  - [x] @ana0

**Comment by RangerMauve** [comment]
@dcwalk Hey! I submitted a PR for adding myself. Is there anything I should change there?

**Comment by eggfroufrou** [comment]
just submitted as well!

**Comment by dcwalk** [comment]
perfect! thanks you two!

**Comment by dcwalk** [comment]
Done! :tada:
