### ISSUE TITLE
Finalize materials for registration package

### ISSUE THREAD

**Issue by dcwalk** [ournetworks/2020#14]
At our `2020-03-28` call we got excited thinking abt what the registration package we'd mail out would look like. At some point we'll need to commit to what is in it!

Kit has:
- Prompts/etc… around what we’re being asked to consider
- ways to hook into treating it more like a game (for those who want it)
- care package as part of registration:
    - ARboxs (stencilled with our logo) -- plastic? 
        - cardboard equivalents?
        - https://ar-cardboards.com/
        - https://www.aliexpress.com/item/32951237253.html
    - stencil with our logo (laser cut)
    - seed care packages (seed bombs?)
    - our own paper with wildflower seeds 
    - core online spaces printed material and set up
        - its a map that we made
    - mail something to another attendee?
    - instruct people to name their wifi to ournetworks
        - wifi config 
        - share your wifinetworks near me images
- Must allow people to “assemble” their own (if they don’t register in time?)

**Comment by dcwalk** [comment]
More notes from [last call](https://raw.githubusercontent.com/ournetworks/2020/master/notes/2020-04-25-planning-meeting.md):

Aspects of the registration package:
- USB key (sneakernets +1 sarah)
    - Digital sneakernet? zine for 
- Something they submit back 
    - Greenscreen/limegreen aesthetic
    - Way that it gets stitched together
    - Registration marks to allow things to go together?
    - "Collaboratively created zoom backround"
    - e.g., ASCII art PRs, A-B-Z ASCII town
- Digital Assets before the conf
    - custom backgrounds
    - skins
- Decoder/code wheels
    - https://www.oldgames.sk/codewheel/
    - feeling this!!! 
    - need that lst minute stress laser cutting deadline to feel alive
    - Somehow coordinate access to sessions with decoder wheel access, 
    - Matching services? coreographing interaction with conf attendees
    - Breakout rooms?
- Group team name as part of registration?
- Comissioning a multiple:
    - good to know in advance
    - shortlist?
- Ship date **JUN 29** everything ready

**Comment by RangerMauve** [comment]
Added to my calendar to look into this tomorrow, gonna do a rough outline of stuff that makes sense / maybe a rough proposal? Then will look at getting something more concrete with DC after the 13th.
