### ISSUE TITLE
Collect ideas on look and feel

### ISSUE THREAD

**Issue by dcwalk** [ournetworks/2020#17]
Migrated from our CFP document, please edit to add text above and drop images/etc... in new comments

### 2020-04-18 Jam notes

- LIME GREEN
- green grassy virtual space
- dc: something permaculture images, succession
- soil layer diagrams
- forest modelling software 
    - {"dynamic spacial interactive landscape"}
- forest inhabitant avatars, drag and drop around the homepage
- kit of parts, can assemble as a place 
- unknown type face
    - "90s hacker wear"
- "tree wave"
    - time, duration
    - looping gifs
    - digital applications of that
- time
    - cyclical
    - koan: "what is the shape of a second hand moving"
- the website grows over time
    - each day of Aug 7-9 weekend we layer on more stuff
        - Have trees that get bigger
    - e.g. more tilesets into Mozilla hubs
- changes colour based on the time of day 
    - dark at night 
    - place you are viewing the website from "based in UTC-X"
    - play with that? offset it?
- events running down side, show every timezone across the side in on times across
- metaflop:
    - typeface that changes over time
    - "build a clock out of a font"
    - variables adjust over time
- Way that people interacting with the site can change it too?
- peoples usage on laptops 
    - "messages in our chat today"
    - low power website representations
- "our own CDN with solar powered pis"

### Inspo

- futuristic p2p and solarpunk aesthetics
- **Solarpunk - Green and a little crusty**
- roleplaying / taking on persona and characters
   - patcon: large device -- if you wanted to use your phone you have to be the person carrying the backpack to be the comms person?
   - 3D print satellite phone housing
- ...
- “If parliamentary politics tends to face inwards towards the existing sense of the possible, then social movements and extra-parliamentary politics have traditionally provided avenues for **the left to face the other way, and develop strategies for “inventing the future”. Over the last three hundred years, the big leaps forward in our collective sense of the politically possible have come from radical social movements, alongside working class organisation.**" - Keir Milburn https://www.versobooks.com/blogs/4592-the-defeat-of-youth-the-generational-dimensions-of-the-2019-general-election
- Renovate the Future: "The truth is: to renovate the future, **we will need a place (virtual for the moment) to work**. And a **variety of tools, by which we mean ideas, old and new**. Let me talk about these ideas for a moment. 
The poet W. H. Auden once suggested that most people carry around in their minds one of two imaginary landscapes: either Eden or Utopia. The Edenic people tend to be liberal arts types, lovers of fantasy, tradition-minded, often religious. Whereas the Utopians are friendly to modern technology, readers of science fiction, analytical, and serious-minded about the world’s problems.
And yet . . . we are no longer in Auden’s Eurocentric world. We are moving into the global Pluriverse, as it’s called — a pluralistic, post-development “world . . . in which many worlds fit,” as the Zapatistas describe it." 
Eutopia Workshops -- https://solidarityhall.org/articles_main/the-eutopia-workshops-our-plan-to-renovate-the-future/

**Comment by dcwalk** [comment]
![02_Uncensored_Library_Fist](https://user-images.githubusercontent.com/4692834/77835988-8ad3fa80-7128-11ea-844b-6f98848bac09.jpg)
![watashi_patema_inverted_bd_1080p_flac115216ed-mkv_snapshot_00-05-15_2014-10-02_15-17-50](https://user-images.githubusercontent.com/4692834/77835990-8c052780-7128-11ea-9513-4cc5d38c5b69.jpg)
![underwater-patema-inverted-sakasama-no-patema-bd-720p-6cb69c7a-mkv_snapshot_01-36-10_2016-05-29_03-24-55](https://user-images.githubusercontent.com/4692834/77835991-8dceeb00-7128-11ea-8c88-571b397888a8.png)
![rtqphx9hvsrrjcgvo1pk](https://user-images.githubusercontent.com/4692834/77835992-8f98ae80-7128-11ea-9d2d-eb3ebc1d42ea.jpg)
![signal-2020-03-26-175313](https://user-images.githubusercontent.com/4692834/77835995-91627200-7128-11ea-8a3d-ef9d87775156.jpeg)

**Comment by dcwalk** [comment]
Thinking 90s:

![52bde4060ed25767608469011ba327e0](https://user-images.githubusercontent.com/4692834/77836228-bbb52f00-712a-11ea-9653-961e9df138f6.jpg)
![935237_1_hackposter_standard_1](https://user-images.githubusercontent.com/4692834/77836230-bce65c00-712a-11ea-96e4-aff54d5b25e5.jpg)
![strange-days-film-elestirisi-hakan-bilge](https://user-images.githubusercontent.com/4692834/77836231-beb01f80-712a-11ea-9279-48a13f8cb28a.jpeg)

**Comment by dcwalk** [comment]
Playing with perspective + organic 
![image-asset](https://user-images.githubusercontent.com/4692834/77836246-e0110b80-712a-11ea-8792-b9f31ecd355b.jpeg)
![permaculture2](https://user-images.githubusercontent.com/4692834/77836247-e1423880-712a-11ea-8679-56004fd15124.jpg)
![Perspective-drawing--RHS](https://user-images.githubusercontent.com/4692834/77836249-e2736580-712a-11ea-9042-6ff368deaa42.jpg)
![isometric-ecosystem-natural-garden-pond-600w-1360316525](https://user-images.githubusercontent.com/4692834/77836251-e43d2900-712a-11ea-83b7-97ed1cde1301.jpg)
![isometric-ecosystem-natural-garden-pond-600w-1360316522](https://user-images.githubusercontent.com/4692834/77836253-eacba080-712a-11ea-9d02-dcfbdb121501.jpg)

**Comment by dcwalk** [comment]
Something about isometric and tiling
![bastion2](https://user-images.githubusercontent.com/4692834/77836259-f919bc80-712a-11ea-90b2-bb2ab6b1cdb8.jpg)
![3690976cdce5d1be0d271050978448d2](https://user-images.githubusercontent.com/4692834/77836262-fa4ae980-712a-11ea-97ca-7cc19d8dccb8.png)
![botanical-garden-icons-set-isometric-various-trees-plants-flowers-decorations-isolated-white-background-d-vector-140608187](https://user-images.githubusercontent.com/4692834/77836264-fc14ad00-712a-11ea-9524-bd08f74f4085.jpg)

**Comment by garrying** [comment]
![Dralli](https://user-images.githubusercontent.com/227587/79282532-78292780-7e83-11ea-852a-d91aabb351c9.jpg)
![Digital-Relics](https://user-images.githubusercontent.com/227587/79282533-78c1be00-7e83-11ea-9a2a-ea5736bee20c.jpg)
> https://unknown-type.com/
 
![file](https://user-images.githubusercontent.com/227587/79284155-cfc99200-7e87-11ea-8346-400c2fbd3e70.gif)

![lpvEI1m4](https://user-images.githubusercontent.com/227587/79282894-4a90ae00-7e84-11ea-89fc-4cf7068c1ecc.png)

![kZTNLzRy](https://user-images.githubusercontent.com/227587/79282900-511f2580-7e84-11ea-9f35-681c4222ee4f.jpg)

![file-1](https://user-images.githubusercontent.com/227587/79285749-72840f80-7e8c-11ea-9d80-9fd84f57d551.gif)

![mz2Jy5ej](https://user-images.githubusercontent.com/227587/79283066-bd9a2480-7e84-11ea-875d-3c2d1efd7204.jpg)

![ASOP_01-f8eb2ac7806f04461b685b351e9c1af9](https://user-images.githubusercontent.com/227587/79283724-a2c8af80-7e86-11ea-84d5-994fbd25d47b.gif)
> https://www.metaflop.com/

![original_f210af1aa29e6153964396a69a3e6a6b](https://user-images.githubusercontent.com/227587/79284053-9bee6c80-7e87-11ea-9335-00cc7f159e92.gif)

![ivG2aoXc](https://user-images.githubusercontent.com/227587/79284238-0d2e1f80-7e88-11ea-9968-c5d76b66bd94.jpg)

![tumblr_ntameeW0aA1r2ws54o1_1280](https://user-images.githubusercontent.com/227587/79284818-c4776600-7e89-11ea-984e-51041e4f774f.jpg)

![Akihiko-Taniguchi-Study-For-A-Post-Photographic-Glossary-2018-03](https://user-images.githubusercontent.com/227587/79285257-0359eb80-7e8b-11ea-9f97-7e7b8920b164.png)

![file](https://user-images.githubusercontent.com/227587/79285660-3355be80-7e8c-11ea-944e-46b0ea5d5f6d.gif)

**Comment by ana0** [comment]
https://www.oldgames.sk/codewheel/

![image](https://user-images.githubusercontent.com/6787392/80285910-348db380-86f6-11ea-82dd-f3b0ed57c2f3.png)
