### ISSUE TITLE
Define requirements and decide what our online hub/anchor space needs

### ISSUE THREAD

**Issue by dcwalk** [ournetworks/2020#19]
The plan:
- Mixed reality main event:
- Remote-first (might have in person)
- **Anchor on/offline “space”** (i.e., mostly Mozilla Hubs) for 2/1.5  days that allows forsSerendipitous interactions
- Satellite “spaces” can be curated and run by others during a longer period, e.g. 4- or 5- days

So, what online hub do we need?
- Somewhere for online people to “meet” and give announcements etc..
- Using our website?
- Chat in webspace, something that could live from start until end, always open, courtyard
- Bridge between virtual space and IRC?

TODOs:
- [x] discuss/document requirements for online hub: https://hackmd.io/Zj4J5d08TSCIhB5h2_A3xw
- [x] identify (additional) technical requirements
- [x] research potential options
- [ ] select!

**Comment by dcwalk** [comment]
Some examples from other confs:
- ICT4Sustainability https://2020.ict4s.org/VirtualParticipation.html BlueJeans + Slido + Google Docs
- ACM User Interface Software and Technology (UIST) https://uist.acm.org/uist2019/online/ Twitch + Mozilla Hubs + Discord
- Accessibility Virtual Reality Group Meetup https://isoc.live/11917/ Mozilla Hubs
- Occupy / Take the Square https://takethesquare.net/2011/10/04/mumble-setup-walkthrough/ Mumble Rooms

**Comment by dcwalk** [comment]
- https://remo.co/conference/
- https://apps.apple.com/us/app/connect-club/id1500718006
- inspo on interfaces the evolve over time: https://apps.apple.com/us/app/living-worlds-mark-ferrari/id1371140984

**Comment by ana0** [comment]
https://town.siempre.io/about

**Comment by dcwalk** [comment]
Notes from co-work here: https://hackmd.io/Zj4J5d08TSCIhB5h2_A3xw

**Comment by ana0** [comment]
Think we did this too!
