### ISSUE TITLE
Develop draft program / formats for conference

### ISSUE THREAD

**Issue by dcwalk** [ournetworks/2020#20]
### Notes from CFP

- Smaller / lead up events 
  - Use Meetup model
  - “Decentralized Socials”
  - HAM study group

Activities that can be submitted:
- Salon talk -- more convo less talk
- Short/very calm 1:1 listen interviews?
- Virtual workshop -- starting in Mozilla Hubs 
- Time-limited study group (MAX 1 month prior to event)
- Something else: online activations
  - https://schloss-post.com/overview/web-residencies/
  - https://thewrong.org/
  - google maps residency: http://www.offsiteproject.org/Google-Maps
  - http://externalpages.org/

Things we're exploring:
- Keynote talk **(Awkward Formal video stream -- full production values)**
  - https://trust.support/watch
- Salon-style talks  (1-2 per night for x amt of time) **(Videoconference)**
- Workshops -> FULL VIRTUAL MULTI-TRACK **(Mozilla Hubs)**
  - Garry Handcrafted web (JR Carpenters at a large scale). Bug twitter ((Flipping through streams of people’s desktops) **(Live/streaming)**
  - http://luckysoap.com/statements/handmadeweb.html
- Study group **(Videoconferencing)**
- HAM
- Using game platforms in unconventional ways (what’s the ournetworks version of twitch plays pokemon?)
- Site specific content for online spaces 
  - tour of http://radio.garden/visit/berlin/6lcXHtKK?
- Video call role playing games about the alternative internet (can we larp on social media?)
- Creating a webring **(Website-based)**
- Guided tour of your desktop **(Live/streaming)**
  - e.g. https://vimeo.com/25832856
  - women's desktops arena board https://www.are.na/claire-l-evans/lovelace-women-s-desktops
- Sign-up during event
- Creating Collections
  - https://9-eyes.com/
- Virtual walking tour
  - Operation Jane's Walk https://vimeo.com/301933682
- Go on a (socially distant) walk
  - Janet Cadiff https://www.youtube.com/watch?v=sOkQE7m31Pw
- Mail … art?
- Commissioned/Bespoke downloads
  - https://left.gallery/
  - https://rhizome.org/download/
- Virtual Murmur Project (Gabe’s thing but online, Google Street View, a website, etc.)
- Public Access Television model
  - https://anthology.rhizome.org/the-world-in-24-hours
  - Reddit PAN https://www.reddit.com/r/pan/
- World in 24 Hours
- Email art happening

**Comment by dcwalk** [comment]
Example of more of a salon short talks format: Jacobin's *Stay at Home* "video education" series https://www.jacobinmag.com/2020/03/stay-at-home-video-series-youtube-jacobin

**Comment by dcwalk** [comment]
This idea of an async public convo is cool: https://galley.cjr.org/public/conversations/-M1QzfNlUBCpQxbikGE1

**Comment by dcwalk** [comment]
Conference in Mozilla Hubs: https://isoc.live/11917/

**Comment by RangerMauve** [comment]
Here's a [recording](https://www.youtube.com/watch?v=tQeBh9DKHXQ) of a talk I did in Hubs earlier this year
