### ISSUE TITLE
advertise CFP! 

### ISSUE THREAD

**Issue by dcwalk** [ournetworks/2020#23]
We should send off the CFP, some places:

- [ ] our toronto networks
  - [x] tomesh
  - [ ] hacklab.to
  - [x] civic tech
    - [x] in person
    - [x] slack
    - [x] calendar
  - [ ] Toronto Students
    - [ ] OCAD (Digital Futures,  Grad Students, Student Union (?))
    - [ ] UofT (U of T decentralized??, CSSU)
    - [ ] York (WISE, Engineering SU)
    - [ ] Ryerson (CSCU)
    - [ ] Seneca
    - [ ] George Brown
  - [ ] other mesh projects:
    - [ ] People's Open
    - [ ] Meta Mesh
    - [ ] NYC Mesh
  - [ ] international:
    - [ ] battlemesh
    - [x] rhizome community board
    - [x] nettime mailing list
    - [x] trust internal chat
    - [x] accessp2p internal chat
    - [ ] APC comm. network letter 
    - ~IFF newsletter and website~ (they no longer advertise)
    - [ ] data & society
    - [x] critical internet studies slack
    - [x] nettime 
  - [x] twitter 
  - [x] ssb
  - [x] our mailinglist
  - [ ] key speakers/groups
     - [x] design justice toronto

**Comment by ana0** [comment]
Closing because this CFP is over
