### ISSUE TITLE
Add server for collecting form submissions

### ISSUE THREAD

**Issue by RangerMauve** [ournetworks/2020#33]
- Figure out how the VM works
- Add minimal service for saving data
- Save to NDJSON
- Have way to extract results into CSV (for the nerds)
- Make sure there's SSL certs in front (nginx)

Get this done this week!

**Comment by RangerMauve** [comment]
Form: https://github.com/ournetworks/ournetworks.ca/blob/5caa3f7d19e606e5b06c426d7f058aa92a713742/sessions-form.html

**Comment by RangerMauve** [comment]
Progress: https://github.com/ournetworks/form-collections

TODO:

- [ ] set up email account
- [ ] Test sending email
- [ ] Configure email properly
- [ ] install on DO
- [ ] configure as systemd service
- [ ] make sure config is being loaded
- [ ] add to nginx config

**Comment by ana0** [comment]
closing because I think we're done?
