### ISSUE TITLE
Publish content moderation policies

### ISSUE THREAD

**Issue by ana0** [ournetworks/2020#34]
Proposal for three tiers

1. Fully moderated space (one of the core team or a trained volunteer is present for the full duration of the event actively moderating)

2. Periodically or partially moderated space (the space is durational and cannot be continuously moderated, but a member of the core team or trained volunteer will check in periodically to check on participants and moderate if needed and/or the space has some moderation tools but they may not be ideal or "complete")

3. Unmoderated space (the space cannot be moderated because of the nature of the platform/artwork/etc ie. it has no moderation tools, please use these spaces at your own risk/discretion, we will do our best to clearly mark them)

We need to:

- [x] confirm categories with presenters if needed
- [x] publish category descriptions on website => https://github.com/ournetworks/ournetworks.ca/pull/207
- [x] include legend or something on conference schedule
- [x] update photo policy to explicitly include screenshots

**Comment by ana0** [comment]
Some notes to consider for what "fully moderatable" means .....

Admins can:
* mute participants
* kick/ban participants
* delete messages that have been posted in a chat

Users can: 
* use a pseudonym
* turn off their own microphone/camera
* leave at any time
* either no dms, or ability to block

**Comment by dcwalk** [comment]
Did this!
