### ISSUE TITLE
ARG

### ISSUE THREAD

**Issue by ana0** [ournetworks/2020#35]
- [x] Communicate to speakers about the experience
- [x] Add into SM tweets
- [x] Integrate into gather.town

**Comment by CyberPopPunk** [comment]
### **ARG Dev Schedule:**
**7/28:** Notebook generic SVG complete

**8/1:** 

- Part 2 Assets complete,
- Email scripts outlines, 
- Automated call scripts generated, 
- Site wireframe complete

**8/4:** 
- Part 3 Assets complete,
-  Network map worksheet finalized,
-  automated calls generated as media,
-  Playtest part 2&3, all contents ordered

**8/8:**
- Part 4 Assets complete,
- Media test,
- Outro script written,
- Compile credits

**8/12:** 
- Revisions from playtesting

**8/15:**
- Playtest Full 2 times,
- Have event scheduled times prepared,
- Packages mailed

**8/19:**
- Playtest revisions

**8/21:**
- SM materials ready and posted,
- Finish any extras/easter eggs

**8/28:**
- Final rundown

**9/4:**
- Last minute leaks n' tweaks

**9/8:**
- CONFERENCE

**9/15:**
- Post Mortem

**Comment by dcwalk** [comment]
Maybe we leave this open until after the postmortem call? => #47

**Comment by CyberPopPunk** [comment]
sounds good
