### ISSUE TITLE
2020 Video Production Assets

### ISSUE THREAD

**Issue by Shrinks99** [ournetworks/2020#40]
It's that time of year again!  I'm creating this issue to track the various assets that we make every year for the live stream.  One goal for this year is to have a little bit of a more dynamic between streams with some actual motion graphics instead of just static images.  I've already begun some [tests for applying the wacky and wild image processing techniques we've got this year in Blender](https://youtu.be/YJ6Fk__c4dE) to make some things move around for the stream and for the intro which I'm stoked about!

Here's all the assets we'll be needing this year (nothing out of the ordinary)
- [x] Lower Third
- [x] Stream Over Graphic
- [x] Up Next Graphic
- [x] Sponsors Graphic
- [x] Video Intro
- [x] YouTube Channel Header
- [x] Video Thumbnail

I will update this issue as I make these assets and move them into a PR in the [artwork](https://github.com/ournetworks/artwork) repo once they become more solidified like last year, if you want me to do otherwise please advise!

**Comment by Shrinks99** [comment]
Lower Third & thumbnail thoughts?  Thumbnail is the same layout as the last two years but with the new styling applied for this year, the symbol that we've had take up that portion of the bottom there can definitely be a different one, in previous years we sorta had a single symbol motif but this year there doesn't seem to be one so I picked a character I thought looked funky.  Didn't use metaflop for the lower thirds as I was worried about readability.

<img width="974" alt="Screen Shot 2020-08-30 at 3 37 25 AM" src="https://user-images.githubusercontent.com/5672810/91653857-29ff7400-ea72-11ea-8985-cd1d16351539.png">
Thumbnail

<img width="1035" alt="Screen Shot 2020-08-30 at 3 36 49 AM" src="https://user-images.githubusercontent.com/5672810/91653861-2b30a100-ea72-11ea-898e-2f4ee27aec47.png">
Lower Third

<img width="981" alt="Screen Shot 2020-08-30 at 3 36 32 AM" src="https://user-images.githubusercontent.com/5672810/91653863-2e2b9180-ea72-11ea-993b-f11dddffc9e7.png">
Lower Third Alt

More funky Blender graphics to come soon!

**Comment by RangerMauve** [comment]
I like the look of the graphics.

I think it'd be nice if the lower third was smaller to have more room for the video contents. Maybe putting it on one line or splitting it to be top/bottom? I don't feel very strongly about this though and it'd be fine as is too.

**Comment by garrying** [comment]
Thumbnail: Okay with me if we're keeping to what we've done previous. I'd also be okay if it were radically different.

My logic for what typeface to use has been: Bold, sans-serif, for session titles. Mono, regular weight, for presenter names. I also feel that they can be the same size.

Lower third: Pixelation, and additional colours, feels a bit off from the vibe. Inclined to keep the lower third solid.

**Comment by dcwalk** [comment]
Agree that pixelation feels like a break from the look!

**Comment by Shrinks99** [comment]
@garrying I'd be cool with radically different thumbnails too, at the moment it's not a priority if this is "good enough" (and also it's a post production thing anyways) but if you have ideas I'd like to see em!

Will ditch the squares in favour of a solid bar like last year, anything we can do to add something neat to it so it's not just a solid bar of green?  Last year we had the caution stripes which were cool....

**Comment by ana0** [comment]
fwiw I kind of like option 2, and the additional colours remind me of our twitter header :woman_shrugging: - if we wanted to do something different maybe we could bring in that image/treatment somehow? maybe smaller pixels might feel more consistent?

**Comment by Shrinks99** [comment]
Okay updates and new graphics!  You can watch them in motion [here](https://www.youtube.com/watch?v=eOoPUxLP1Ts), you'll have to imagine them moving below though.  After a few different tracking shots it will dissolve to the top-down angle and the pixels all fall into place to form the image, then the video loops.  Seeing as the conference is all online this year I wanted to do something a little more dynamic that still works with the branding.

<img width="1084" alt="Screen Shot 2020-09-05 at 3 04 58 AM" src="https://user-images.githubusercontent.com/5672810/92299968-09796300-ef25-11ea-807b-5db661b6ff1c.png">

I've put the sponsors and up-next graphics on different screens this year which will also transition between each-other as we stream.  I think I'll ditch the green background and just tilt the camera down so only the moving pixel columns are in frame.

<img width="1083" alt="Screen Shot 2020-09-05 at 3 04 49 AM" src="https://user-images.githubusercontent.com/5672810/92299970-0ed6ad80-ef25-11ea-888d-008a05b95ed8.png">

The lower third pixels have been removed.  I can't make the talk name text any larger (gotta be able to accommodate the longest talk name) but I can make the presenter names smaller @garrying.

<img width="1058" alt="Screen Shot 2020-09-05 at 3 07 35 AM" src="https://user-images.githubusercontent.com/5672810/92299972-0f6f4400-ef25-11ea-9b10-76df1edfb86e.png">

The last bit of this (stretch goal!) is to generate new renders for the stream so we have one per-day of streaming!  This is actually much easier than you might think because all the animation (except for the camera moves) is fully procedural and the height of the pixels is based on their luminance.  If you have image suggestions (they just need to be 16x9 and look decent at a resolution of 214 × 120 pixels) send 'em over!!  Once I have enough images I can just plug them all into Blender, queue them up and we're good to go, all the hard work there is already finished.

**Comment by Shrinks99** [comment]
Updated video with more clips and slightly different camera angles — this is representative of what I'd like the final video to look like in OBS, it loops.  https://youtu.be/yjLfDGLwRgE

**Comment by garrying** [comment]
I'm okay with moving forward with this. Additional thoughts:
- The lower third: Preferring smaller presenter names
- Could we add text next to the Interchain logo? We can use what was done in the mailout here: https://github.com/ournetworks/artwork/blob/1a33c830322ae4955186e327cd571509f75f389e/2020/mailout/2020-mailout-letter.pdf
- For the stretch goal of generating new renders, we could use what's in this are.na channel that is in the public domain. The imagery I've been using has been coming from it. https://www.are.na/jack-f/pubdomordie

**Comment by Shrinks99** [comment]
[2020 intro link!  Check it out!](https://www.youtube.com/watch?v=V2S-KgnuBXc)

**Comment by dcwalk** [comment]
Hey @Shrinks99 can you PR these assets into https://github.com/ournetworks/artwork/? Then we can close out this issue :pray:
