### ISSUE TITLE
Develop sponsorship package and pipeline

### ISSUE THREAD

**Issue by dcwalk** [ournetworks/2020#7]
We should develop a new sponsorship package (are there modifications we want to make from last year?!)!

TODOs:
- [x] [initial draft](https://docs.google.com/document/d/19wMPA6Mt7rE6SEqdUy7DGc6Av75aO_V6-pxUS5InN7k/edit#)
- [x] collective review
- [x] create pipeline
- [x] final first version of package locked down

**Comment by RangerMauve** [comment]
Started draft of 2020 sponsorship package from the 2019 one.

https://docs.google.com/document/d/19wMPA6Mt7rE6SEqdUy7DGc6Av75aO_V6-pxUS5InN7k/edit#

Honestly, I think most of the stuff still makes sense. Some of the stuff like having a table of marketing materials and having logos on a podium won't work in meatspace. Though maybe we can figure out an analog in cyberspace? Something like "Your logo on the virtual podium".

Will fill in more deetz when #21 and #19 are like.

Also, what's the audience? Same as before?

**Comment by dcwalk** [comment]
We did this! Yess! We should spawn an issue to track sponsor outreach
