### ISSUE TITLE
Find a venue for large in-person event

### ISSUE THREAD

**Issue by dcwalk** [ournetworks/2020#9]
Requirements:
- 100-150 attendees
- accessible space!
- affordable!

TODOs to mark as done:
- [ ] research possible venues
- [ ] submit booking requests with venues in order:
- [ ] confirm costing details
- [ ] finalize venue agreement

---

Potentials:
- [TMAC](https://www.tomediaarts.org/)
   - capacity: > 100
- Mozilla Community Space
  - capacity 80 - 110
  - accessibility: rear entrance
- [Array Space](https://www.arraymusic.ca/array-space/about-array-space) ⛔
- [Unit 2](http://unit2.club/book-the-space)
- [Geary Lane](http://gearylane.com/) That warehouse space on geary??
- 918 Bathhurst http://918bathurst.com/renting/ (I asked before and they are expensive) 🕳 📑
- Trinity St Paul's Gym (sound isn't great) https://www.trinitystpauls.ca/rentals/ 📑
- Steelworkers Hall

Key:
⛔ not fully accessible
📑 rental agreement requirements
🕳 small
💰 expensive

**Comment by RangerMauve** [comment]
Hoping to spend some time on this on Wednesday.

What sorts of steps should I do? Should I look into the details in the venues to double check if they're fully accessible and stuff?

**Comment by dcwalk** [comment]
With COVID-19 uncertainty (#11) we may want to chat on call tomorrow before proceeding, but roughly, we're still in the research phase. 

Mostly it's trawling/searching for venues that fit the criteria at the top of the issue (size, date range), understanding their price/fee model, and then recording that in this issue. We'll probably have to make some emails and calls to understand that stuff too.

I think Steelworkers Hall is a great option! I think TMAC is too! Potentially Trinity St Paul's Gym too?

**Comment by dcwalk** [comment]
We're parking this search for now given the unfolding COVID-19 situation (#11), per discussion on `2020-03-14`: https://github.com/ournetworks/2020/blob/master/notes/2020-03-14-planning-meeting.md. Marking `wont-do` and we'll make a new issue closer to
